### ISSUE TITLE
Google

### ISSUE THREAD

**Issue by ameliadewolfe** [ameliadewolfe/SAfA#2]
-make a google account
-acquaint yourself with google drive 
-explore google doc features

**Comment by Endale10** [comment]
Do you mean a regular Gmail account?

**Comment by ameliadewolfe** [comment]
Hi Endale, yes. I'm pretty sure that google services have merged, so you should have your own google drive once you set up a gmail account. If this doesn't work out, please make a note either here or in slack and we can figure it out.

**Comment by Endale10** [comment]
ok thanks for the clarification.

**Comment by Endale10** [comment]
Hello. How are the Himalaya's? Is the meeting on video or in person? If
it's in person where would it be taking place?
Endale

**Comment by Endale10** [comment]
Hi there.I'm really sorry for the late notice. I can't come today because I
have a lot of things on my plate right now. I just wanted to find out what
I would be missing. So besides the flyers being giving out, will there be
anything else I will be missing?
